django/pypro/base/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

django/pypro/builtin_functions/urls.py
from . import views
from django.urls import path

app_name = "builtin_functions"
urlpatterns = [
    path('', views.index, name='functions'),
    path('/<str:func_name>', views.detail, name='detail')
]

django/pypro/pypro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('builtin_functions', include('builtin_functions.urls'))
]

django/pypro/base/models.py
from django.db import models

# Create your models here.

django/pypro/builtin_functions/models.py
from django.db import models

# Create your models here.


"""class BuiltInFunctions(models.Model):
    name = models.CharField("Функция", max_length=20, unique=True)
    syntax = models.TextField("Синтаксис")
    short_description = models.CharField("Короткое Описание", max_length=200)
    description = models."""

django/pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html', {'title': 'PyPro'})

django/pypro/builtin_functions/views.py
from django.shortcuts import render
from django.http import Http404
from io import StringIO
import sys
import importlib
from . import scripts
# Create your views here.


class OutputInterceptor(list):
    def __enter__(self):
        self._stdout = sys.stdout
        sys.stdout = self._stringio = StringIO()
        return self

    def __exit__(self, *args):
        self.extend(self._stringio.getvalue().splitlines())
        del self._stringio
        sys.stdout = self._stdout


def index(request):
    context = {}
    alphabetic_list = []
    functions = [i for i in __builtins__ if i[0] in [chr(j) for j in range(97, 123)]]
    functions.sort()
    for i in functions:
        if len(alphabetic_list) > 0:
            if alphabetic_list[0][0] == i[0]:
                alphabetic_list.append(i)
            else:
                context[alphabetic_list[0][0]] = alphabetic_list
                alphabetic_list = []
        else:
            alphabetic_list.append(i)
    return render(request, 'builtin_functions/functions.html', {'f_list': context})


def detail(request, func_name):
    """Отображение детальной информации о функции"""
    # Путь к файлам с примерами и добавление в path
    path = 'C:\\studying\\python\\built_in_functions'
    sys.path.append(path)
    # Получение отсортированного списка всех встроенных функций в Python для навигации
    func_list = [i for i in __builtins__ if i[0] in [chr(j) for j in range(97, 123)]]
    func_list.sort()
    # Отсортировка запросов которые не относятся к функциям
    if func_name not in func_list:
        raise Http404

    with open(path + f"/_{func_name}.py", encoding='utf-8') as file:
        comment = False
        pos = 'syntax'
        description_string = ''
        file_content = {
            'syntax': [],
            'description': [],
            'example': [],
        }
        for line in file:
            code_str = line.rstrip()
            if code_str == '"""':
                if comment is False:
                    comment = True
                    continue
                else:
                    comment = False
                    file_content[pos].append(description_string)
                    pos = 'example'
                    continue
            if pos == 'syntax':
                if code_str == '':
                    pos = 'description'
                    continue
                else:
                    file_content[pos].append(code_str)
            if pos == 'description':
                if code_str == '':
                    file_content[pos].append(description_string)
                    description_string = ''
                    continue
                else:
                    description_string += code_str
                    if description_string[-1] != '.':
                        description_string += ' '
            if pos == 'example':
                if code_str == '':
                    file_content[pos].append('\n')
                else:
                    file_content[pos].append(code_str)

    # Получение результата выполнения
    with OutputInterceptor() as res:
        """Через exec плохо не работает с aiter:
        with open(path + f"\_{func_name}.py") as file:
            exec(file.read())"""
        i = importlib.import_module(f"_{func_name}")

    if not res:
        with OutputInterceptor() as res:
            importlib.reload(i)

    print(file_content['syntax'])

    context = {'func_name': func_name,
               'title': f"Встроенная функция {func_name}",
               'func_list': func_list,
               'syntax': file_content['syntax'],
               'description': file_content['description'],
               'example': file_content['example'],
               'result': res,
               }
    return render(request, 'builtin_functions/detail.html', context)


def detail_new(request, func_name):

    func_list = [i for i in __builtins__ if i[0] in [chr(j) for j in range(97, 123)]]
    func_list.sort()

    context = {'func_name': func_name,
               'title': f"Встроенная функция {func_name}",
               'func_list': func_list,
               'syntax': f"builtin_functions/{func_name}/syntax.html",
               }
    return render(request, 'builtin_functions/detail.html', context)

django/pypro/base/templates/base/basic_bottom.html
        <footer>
        Код внизу страницы
        </footer>
    </div>
</body>
</html>

django/pypro/base/templates/base/basic_top.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link rel="shortcut icon" href="{% static 'base/icon.png' %}" />
    <link rel="stylesheet" href="{% static 'base/base.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <div class='page'>
        <section class="hat">
            <div class="hat-leftblock">
                <div class="hat-leftblock-logo">
                    <a href="\">PyPro</a>
                </div>
            </div>
        </section>

django/pypro/base/templates/base/home.html
{% include "base/basic_top.html" %}
<main class="face">
    <h1 class="face-h1">PyPro</h1>
    <h2 class="face-h2">Справочник python</h2>
    <div class="face-flexblock">
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
        <div class="face-flexblock-block">
            <a href='{%url "builtin_functions:functions" %}'>Встроенные функции</a>
        </div>
    </div>

</main>

{% include "base/basic_bottom.html" %}

django/pypro/builtin_functions/templates/builtin_functions/abs/description.html
<p>Описание</p>

django/pypro/builtin_functions/templates/builtin_functions/abs/syntax.html
<div class="syntax">
    <p>abs(obj) -> int/float</p>
</div>

django/pypro/builtin_functions/templates/builtin_functions/common_footer.html
</body>
</html>

django/pypro/builtin_functions/templates/builtin_functions/common_top.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'builtin_functions/style.css' %}">
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>

django/pypro/builtin_functions/templates/builtin_functions/detail.html
{% include "builtin_functions/extend_styles.html" %}
<div class="flex-block">
{% include "builtin_functions/functions_nav.html" %}
<main>
  <h1>Встроенная функция {{func_name}}</h1>
  <h2>Синтаксис</h2>
  <div class="syntax">
    {% for item in syntax %}
      <p>{{item}}</p>
    {% endfor %}
  </div>
  <h2>Описание</h2>
  {% for item in description %}
  <p>{{ item }}</p>
  {% endfor %}
  <h2>Пример</h2>
<pre class="example">
{% for item in example %}<code>{{ item }}</code>{% endfor %}</pre>
  <h2>Результат</h2>
<pre class="example">
{% for item in result %}<code>{{ item }}</code>{% endfor %}</pre>
</main>
</div>
{% include "base/basic_bottom.html" %}

django/pypro/builtin_functions/templates/builtin_functions/detail_new.html
{% include "builtin_functions/extend_styles.html" %}
<div class="flex-block">
{% include "builtin_functions/functions_nav.html" %}
<main>
  <h1>Встроенная функция {{func_name}}</h1>
  <h2>Синтаксис</h2>
  {% include syntax %}
  <h2>Описание</h2>
  {% for item in description %}
  <p>{{ item }}</p>
  {% endfor %}
  <h2>Пример</h2>
<pre class="example">
{% for item in example %}<code>{{ item }}</code>{% endfor %}</pre>
  <h2>Результат</h2>
<pre class="example">
{% for item in result %}<code>{{ item }}</code>{% endfor %}</pre>
</main>
</div>
{% include "base/basic_bottom.html" %}

django/pypro/builtin_functions/templates/builtin_functions/extend_styles.html
{% extends "base/basic_top.html" %}
{% load static %}
{% block styles %}<link rel="stylesheet" href="{% static 'builtin_functions/style.css' %}">{% endblock styles%}

django/pypro/builtin_functions/templates/builtin_functions/functions.html
{% include "builtin_functions/extend_styles.html" %}
<main class="one-column">
    <h1>Встроенные Функции</h1>
      {% for item,value in f_list.items %}
      <div class="f-letter">{{item|capfirst}}</div>
      <ul class="f_list">
          {% for val in value%}
          <li><a href="{% url 'builtin_functions:detail' val %}">{{val}}</a></li>
          {% endfor %}
      </ul>
      {% endfor %}
  </main>
{% include "base/basic_bottom.html" %}

django/pypro/builtin_functions/templates/builtin_functions/functions_nav.html
<nav class="column-nav">
  <ul>
    {% for item in func_list %}
    <li><a href="{% url 'builtin_functions:detail' item%}">{{item}}</a></li>
    {% endfor %}
  </ul>
</nav>

django/pypro/builtin_functions/templates/builtin_functions/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'builtin_functions/style.css' %}">
    <meta charset="UTF-8">
    <title>Built-in functions</title>
</head>
<body>
  <main class="one-column">
    <h1>Built-in functions</h1>
      {% for item,value in f_list.items %}
      <div class="f-letter">{{item|capfirst}}</div>
      <ul class="f_list">
          {% for val in value%}
          <li><a href="{% url 'builtin_functions:detail' val %}">{{val}}</a></li>
          {% endfor %}
      </ul>
      {% endfor %}
  </main>
</body>
</html>